# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+startup: overview indent

* Devotionals

This includes devotional notes from daily readings and mediations.


** The Gospel According to John

I have undertaken a reading of this Gospel with a beloved friend and brother in
Christ. These are my notes from the reading.

*** John 1 (2025.06.20)

This is an intense chapter, so full and so rich. Major themes that strike me today:

**** God has drawn near to us

This passage tells us how God, in His generosity, has drawn near to us. It tells
us where He came from: from eternity past. He didn't have to create the
universe, and He didn't have to create us.

Some have said that He needed to create us, because God is Love; and, Love needs
an object to be fully expressed. Yet, this is a mistaken notion for a few
reasons. First, God had perfect love since eternity past in the perfect
communion of the Trinity. Second, God does not need anything, since He is
self-sustaining and not lacking in anything, since He is the source of all
things.

Why did He create us despite knowing how it would all unfold? Out of His
generosity. And, despite our sin and rebellion, He came to us (verse 1:14) in
the flesh. How great a mystery is this that the eternal, immaterial, and
unchanging Son--the Creator--would integrate with His creation by taking on a
finite, physical, and temporal human body, vulnerable and helpless
as a baby?!? And why did He do this? So that He could draw near to us and draw
us near to Himsel! And in His nearness to us, He brings us life (for He is the
source of life itself) and light for He is the source of all existence and
reality, and truth is the revelation of reality.

The picture of a cosmic approach of God to humanity becomes even more personal
as we are told of Christ approaching John the Baptist.

**** God draws men near to Himself

In verse 36, we begin to see Jesus draw men to know Him and to follow Him.

**** The Mystery of the Incarnation

In chapter 1, we see a great mystery: the Creator, the Word, the author of Life,
is disguised, hidden, and unseen; yet, He is present in human form as an
ordinary man. To see the God in this Man takes an act of faith and a willingness
to look at what appears normal; or maybe, since I have read this Gospel many
times, a willingness to look at what I have seen before and be open to learning
more. Nathaniel heard of Jesus and wondered if anything worthwhile could come
from Nazareth. Nonetheless, after talking to Jesus, he was willing to say, "You
are the Son of God! You are the King of Israel."







**** The Baptism
Christ is Himself baptized by John the Baptist. We now have the testimony of
John the Baptist for Jesus as being the Son of God; and we have the sign from
the Holy Spirit, signifying and confirming this.

*** John 2 (2025.06.21)

This chapter opens with a marriage at Cana, where the mother of Jesus
was. Interestingly, it states that "Jesus also was invited to the marriage, with
his disciples."

I see here Mary, the mother of Jesus, as an instigator of grace. She presented
Jesus with the predicament faced by the wedding celebrants: "They have no wine."

Christ's response was "My hour has not yet come," indicating that it was not His
will to do anything about it. It was not His will to initiate His
public ministry. Yet, Mary, His mother, goads Him on. In her faithful way,
commends the servants to Jesus, pointing them to Him and telling them, "*Do
whatever He tells you*." She has this way of bringing the needy to the Provider,
and instigating a move by the Provider. While this may appear strange to
Protestant eyes because they are not accustomed to thinking of Mary as an
instigator of grace, we also can recognize this in the conception (type) of Mary
as the New Eve. Just as Eve was called "woman" in Genesis, Jesus--through
John--highlights the connection between Mary and Eve as He calls her "woman."
This is an honorable reference, not a denigrating treatment of His mother, as we
modern-day Americans could understand this. For us Catholics, this can encourage
us to *involve Our Mother as a prayer partner and intercessor*, and yet to *fully
trust and obey Jesus*.

I love this detail about how the best wine comes last (verse 2:10). It reminds
me of how in a life with Jesus, our love for Him and the sweetness of our
relationship can--and should--increase with time. He is the joy, hope and
sweentess of our lives, and this joy, hope, and sweetness should increase in
depth and intensity as we progress through life.

Next, we see the cleansing of the temple. Here, Christ drives out the
money-changers, who sought to take advantage of the faithful. When asked for His
authority to do this, or what is the point, Jesus' response is, "Destroy this
temple, and in three days I will raise it up." John is careful to bring out the
meaning of this: it's tied to His body, and His resurrection.

Now, His ministry had begun, and many began to beileve in Him because of His
signs (2:23).

*Take-aways*: pray with Mary; trust and obey Jesus; submit to His authority in
all things; stay close to Him in the Eucharist, His Body, which makes present
to us His death and resurrection.

*** John 3 (2025.06.22)

Ths
