# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+startup: overview indent

* Devotionals

This includes devotional notes from daily readings and mediations.


** The Gospel According to John

I have undertaken a reading of this Gospel with a beloved friend and brother in
Christ. These are my notes from the reading.

*** John 1 (2025.06.20)

This is an intense chapter, so full and so rich. Major themes that strike me today:

**** God has drawn near to us

This passage tells us how God, in His generosity, has drawn near to us. It tells
us where He came from: from eternity past. He didn't have to create the
universe, and He didn't have to create us.

Some have said that He needed to create us, because God is Love; and, Love needs
an object to be fully expressed. Yet, this is a mistaken notion for a few
reasons. First, God had perfect love since eternity past in the perfect
communion of the Trinity. Second, God does not need anything, since He is
self-sustaining and not lacking in anything, since He is the source of all
things.

Why did He create us despite knowing how it would all unfold? Out of His
generosity. And, despite our sin and rebellion, He came to us (verse 1:14) in
the flesh. How great a mystery is this that the eternal, immaterial, and
unchanging Son--the Creator--would integrate with His creation by taking on a
finite, physical, and temporal human body, vulnerable and helpless
as a baby?!? And why did He do this? So that He could draw near to us and draw
us near to Himsel! And in His nearness to us, He brings us life (for He is the
source of life itself) and light for He is the source of all existence and
reality, and truth is the revelation of reality.

The picture of a cosmic approach of God to humanity becomes even more personal
as we are told of Christ approaching John the Baptist.

**** God draws men near to Himself

In verse 36, we begin to see Jesus draw men to know Him and to follow Him.

**** The Mystery of the Incarnation

In chapter 1, we see a great mystery: the Creator, the Word, the author of Life,
is disguised, hidden, and unseen; yet, He is present in human form as an
ordinary man. To see the God in this Man takes an act of faith and a willingness
to look at what appears normal; or maybe, since I have read this Gospel many
times, a willingness to look at what I have seen before and be open to learning
more. Nathaniel heard of Jesus and wondered if anything worthwhile could come
from Nazareth. Nonetheless, after talking to Jesus, he was willing to say, "You
are the Son of God! You are the King of Israel."







**** The Baptism
Christ is Himself baptized by John the Baptist. We now have the testimony of
John the Baptist for Jesus as being the Son of God; and we have the sign from
the Holy Spirit, signifying and confirming this.

*** John 2 (2025.06.21)

This chapter opens with a marriage at Cana, where the mother of Jesus
was. Interestingly, it states that "Jesus also was invited to the marriage, with
his disciples."

I see here Mary, the mother of Jesus, as an instigator of grace. She presented
Jesus with the predicament faced by the wedding celebrants: "They have no wine."

Christ's response was "My hour has not yet come," indicating that it was not His
will to do anything about it. It was not His will to initiate His
public ministry. Yet, Mary, His mother, goads Him on. In her faithful way,
commends the servants to Jesus, pointing them to Him and telling them, "*Do
whatever He tells you*." She has this way of bringing the needy to the Provider,
and instigating a move by the Provider. While this may appear strange to
Protestant eyes because they are not accustomed to thinking of Mary as an
instigator of grace, we also can recognize this in the conception (type) of Mary
as the New Eve. Just as Eve was called "woman" in Genesis, Jesus--through
John--highlights the connection between Mary and Eve as He calls her "woman."
This is an honorable reference, not a denigrating treatment of His mother, as we
modern-day Americans could understand this. For us Catholics, this can encourage
us to *involve Our Mother as a prayer partner and intercessor*, and yet to *fully
trust and obey Jesus*.

I love this detail about how the best wine comes last (verse 2:10). It reminds
me of how in a life with Jesus, our love for Him and the sweetness of our
relationship can--and should--increase with time. He is the joy, hope and
sweentess of our lives, and this joy, hope, and sweetness should increase in
depth and intensity as we progress through life.

Next, we see the cleansing of the temple. Here, Christ drives out the
money-changers, who sought to take advantage of the faithful. When asked for His
authority to do this, or what is the point, Jesus' response is, "Destroy this
temple, and in three days I will raise it up." John is careful to bring out the
meaning of this: it's tied to His body, and His resurrection.

Now, His ministry had begun, and many began to beileve in Him because of His
signs (2:23).

*Take-aways*: pray with Mary; trust and obey Jesus; submit to His authority in
all things; stay close to Him in the Eucharist, His Body, which makes present
to us His death and resurrection.

*** John 3 (2025.06.22)

Ths

** Genesis
I list some major themes I identify as I read through Geneisis in the summer of 2025.
1. All of life is a test: will I follow and obey my will, or God's will?
   1. This presupposes that I have the freedom to choose to obey God's will or
      reject it.
   2. Obedience to God's will is the pivotal question in life. It is the key to
      the Lord's prayer: "Hallowed be Thy name. Thy kingdom come, Thy will be
      done, on earth as it is in heaven." In the Gospel, Christ speaks as if the
      kingdom of heaven is at hand, or as if it has come. It has come, indeed,
      in a hidden and mysterious way; it has not yet been fully revealed or
      consummated on earth. Yet, when we obey God, we manifest His kingodm as
      ambassadors, agents, or operatives of His kingdom.
   3. We are given an intellect and a will. With the intellect, we can know God,
      and with the will, we can obey God, which leads to an experiential knowing
      of God, and a personal knowledge of God.
   4. Examples:
      1. Adam and Eve.
         1. They were presented with God's will in the garden, to live by His
            command and within His boundaries.
         2. In this story, we learn that we are not alone or isolated as we are
            faced with the choice to do God's will or to choose our own way:
            there is an enemy who hates God, and he hates us because we are made
            in God's image, and God loves us.
            1. The enemy's desire is to thwart or God's love for us by getting
               us to disobey God, for he knows that in obedience to God's will,
               we have life abundant; but in disobedience, we have death that
               grieves God and destroys us forever
            2. The enemy's objective is to get us to disobey and reject God's
               will by:
               1. Confusing us
               2. Having us question God's will, His plan, and ultimately, His
                  goodness intent toward us
               3. Causing us to be in fear, and thus to act blindly or foolishly
                  in ways contrary to God's will
         3. The temptation that Adam and Eve faced is the same as the temptation
            that we face, and all those who came before us or will come after us
            face: do we receive God's will as good and good for us, or do we
            reject it in favor of our own vision, our own glory, or our own
            desires and passions?
      2. Cain and Abel. Cain's sacrifice was lacking in some way, and God said
         that sin was crouching at his doorstep. Cain refused to repent, and in
         jealousy and perhaps pride, he added to his sin by killing his brother.
      3. Enoch. Enoch walked with God and was no more. Apparently, he chose
        God's will, and he walked in friendship with God.
      4. Noah. He accepted God's task in faith to build an ark, despite the
        fact that it took hundreds of years, and there is no evidence that
        he even saw rain or flooding until the Great Flood.
      5. The sons of Noah. Ham committed a great evil against his father by
         "looking upon the nakedness of his father," and
         Shem and Japheth chose to instead to cover the shame of their father.
   5. Abraham
      1. Abraham and Hagar. Having received the promise of God of abundant
         descendants, Abraham and Sarah apparently saw the sitation as
         impossible, for Abraham was very old and Sarah was barren. They did not
         know that nothing is too difficult for God, and they did not trust His
         ability to fulfil His promise without their help or their action. So,
         Sarah convinced Abraham to father a child through her handmaid, which
         may have been a common practice in the ancient middle east. But, we who
         follow Christ are not called to common practices, but rather
         extraordinary lives.
      2. Abraham and the King (x2). Having recieved the promise of abundant
         descendants, Abraham feared for his life. On two occasions, he lied
         and said that Sarah was not his wife, but his sister; for she was very
         beautiful. He feared that he would be killed so that she could be
         taken. Apparently, Abraham's fear was greater than his faith in God's
         promise.
      3. Abraham and the Sacrifice of Isaac. Having recieved the promise of abundant
         descendants, Abraham was instructed to sacrifice his only son, whom he
         loved. This was the son who was to inherit Abraham's covenant and
         blessing. Now, Abraham had grown in his faith and trust in God to
         beleive that even if he were to obey God, God would raise Isaac from
         the dead so that He could fulfill His promise and His covenant.
      4. Abraham and Lot.
   6. Isaac and the King. Isaac also had an episode where he lied about
      Rebeccah, his wife. He said she wasn't his wife.
   7. Jacob. He spent his early life lying and conniving to get his way, notably
      in deceiving his brother to give up his birthright and to get his father
      to bless him as the firstborn in the place of Esau, his brother. This led
      to being on the run for decades, where Jacob himself was cheated by his
      uncle Laban. Eventually, Jacob left Laban, and he encountered God in such
      a way his ability to run and flee was broken. Jacob was now left trusting
      in God as he faced the possible wrath of his brother Esau, who at one
      point sought to kill Jacob.
   8. Joseph and his brothers.
2. All of life is an invitation to know God, to pursue Him, and to be loved by
   Him.
   1. Personal invitations
      1. In creation--and in our personal creation--God gives us our first
         invitation to know him.
      2. As we grow through childhood, we develop and intelect and a will, which
         enable us to know God personally through faith (knowledge), hope
         (trust), and love (obedience).
      3. At some point, we are invited to make the faith personal, to enter into
         a personal relationship with Jesus Christ.
   2. Cain was called to repent and to offer a better sacrifice.
   3. Abraham was called to leave his father's household and journey to a land
      that God had not yet shown to him.
      1. What if Abraham had refused to go, or if he had said, "This can't be
         real. I'm making this up"?
   4. Abraham was called to:
      1. Follow God on an unknown path, to step out of his comfort zone to a
         journey with God.
      2. live a life in light of God's promise to bless the
         world though his innumerable descendants.
   5. Joseph
      1. Since his youth, Joseph had been experiencing and dealing in dreams. He
         had his own dreams, and he ws favord by his father above his brothers.
         1. This favoritism bred contempt and hatred and jealousy among his
            brothers for Joseph.
      2. Great evil was done to Joseph: his brothers sought to kill him, but
         settled for selling him into slavery.
      3. Joseph found hound himself a slave to Potiphar, and there, he found
         great favor from God with Potiphar.
      4. Soon--because of Potiphar's wife--Joseph was in the prison of Pharaoh
         1. Potiphar could easily have killed Joseph for betraying him, but
            he didn't.
         2. Perhaps, by the grace of God, Potiphar knew Joseph's character
            and that of his own wife, and so to protect Joseph, he had him
            imprisoned elsewhere and away from Mrs. Potiphar.
         3. Nonetheless, this was not for Joseph's
      5. We see reflections of Christ in Joseph:
         1. "Behold, this is my beloved Son, in whom I am well pleased."
         2. Jospeh was innocent in all things, but he was betrayed by his brothers.
         3. In a type of Christ's resurreciton, Joseph was abased in prison,
            and later lifted up and exalted to the right hand of the king
            Pharaoh, and he was given power and dominion over all of Egypt
         4. We see Joseph forgive his brothers, recalling Christ's words,
            "Forgive them, for they know not what they do."
