# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+startup: overview indent


* Belief in the Real Presence of Christian

It’s amazing. For the first 1500 years of Christianity, Christians believed that
it was. John 6 says it is. John’s student, Ignatius of Antioch (died around
108-110 AD) said it’s literally the body and blood of Jesus, and so did Justin
Martyr in writings (around 155 AD). Even Martin Luther believed that it
was. There was a reformer named Zwingli who didn’t think things were changing
enough. He debated Martin Luther in the 1520s (as early as 1521 and as late as
1519), Luther defending the Real presence, and Zwingli saying that communion is
just a symbol. I had to say, “Wow, I guess I was taught wrong.”  Either the
first 1500 years of Christians got it wrong, or maybe they were right. 

The reason for the reverence you see is because of the belief that the Eucharist
is really the body and blood of Jesus Christ Himself. That’s the power Mass: to
be present with Jesus as He gives Himself to us, and we give ourselves fully to
Him. It’s also the power of adoration: it’s being with Him physically, looking
at Him, and letting Him gaze back at me. If it’s just a piece of bread, then
everything becomes meaningless.

