# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+startup: overview indent


* Truth
:PROPERTIES:
:CUSTOM_ID: truth
:END:
It is helpful to begin with the concept of *truth*, because if there is no truth, then
there is no point in discussion. We show first that *there must be truth*;
and second, that *truth is absolute*. Along the way, we pick up an important
tool, *the principle of non-contradiction*, which we can use to demonstrate that
some ideas (or propositions) are invalid and must be rejected.
** There _must_ be Truth
:PROPERTIES:
:CUSTOM_ID: there-must-be-truth
:END:

An important starting point is truth. Truth must exist, and it must be
absolute. If not, then why do we even spend time talking, discussing, and
debating? Why not allow everyone to go off on their own and manifest his or her
own reality as he or she sees fit? Clearly this is absurd.

We can more rigorously conclude that /there must be truth/ if we start with the
another antithetical proposition, which we call *proposition A*:
#+begin_info
*Proposition A* \\
There is no truth.
#+end_info
The problem with proposition *A* arises when we ask, "Is *A* true?" If the
response is *yes*, then a truth exists, and *A* becomes false. This is a
contradiction, and it cannot possibly be valid according to the rules of logic,
namely the principle of non-contradiction.

*** The Principle of Non-contradiction
The principle of non-contradiction is a law of logic:
#+begin_info
*The Principle of Non-Contradiction* \\
A proposition cannot be both true and false at the same time in the same respect.
#+end_info

This is foundational to logical reasoning and coherent thought.

The principle--sometimes called a *law*--of non-contradiction tells us that
/there is no truth/ is invalid, and it must be rejected. If we reject /there is
no truth/, then we are left with the principle that *there _must_ be truth*.

This is comforting when we remember Jesus Christ claimed to be the Way, the Truth, and
the Light. The truth is something foundational and concrete.

#+begin_info
*More on the Principle of Non-contradiction*

#+html: <details>
#+html: <summary>Learn more about this ...</summary>

For more information on this topic, you may wish to watch or listen to the following:
#+html: <iframe width="560" height="315" src="https://www.youtube.com/embed/YLl7TRF_l2w?si=LcYPcWhI_7TFe1u_" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

#+html: <iframe style="border-radius:12px" width="560" src="https://open.spotify.com/embed/episode/23kgVmvxZWK46CutGq3w5K?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

#+html: </details>
#+end_info

** Truth is Absolute
:PROPERTIES:
:CUSTOM_ID: truth-is-absolute
:END:

Let's try another statement, *proposition B*:
#+begin_info
*Proposition B* \\
There is no absolute truth.
#+end_info
We can explore the validity of *B* in much the same way as we did for *A*. We can ask if *B* is 
/absolutely/ true. If the answer is yes (it is absolutely true)--as so many who
would invoke proposition *B* would like us to believe--, then *B* has negated
itself, again becoming absurd and invalid. Now, not only can we conclude that
*there must be truth*, but also that *truth is absolute*.

** Faith and Reason
:PROPERTIES:
:CUSTOM_ID: faith-and-reason
:END:

Now that we know that *truth exists*, and reason can help us access truth, we
might want to consider the relationship between faith and reason. By reason, we
can uncover truth through deduction; and the scientific method--built on
induction--is an extension of reason by which we can uncover truths about the
created universe. Also, we have noted that by reason, we can uncover truth about
the cause of the universe because of what we know about the universe through
observation.

But, what about faith? Faith is reception of or tust in the testimony of others
about things we are not able to observe directly nor reason about directly. We
use faith in the practical world on a regular basis. For example, we ask someone
where to find a place or a thing; they tell us, and we follow their
instructions. In the realm of faith in God, we receive revelation from God
through the Church or the Scriptures. This is often information we cannot obtain
through reason alone. For example, we could reason that God exists, but we could
not obtain without revelation that God is one being in the Persons of Father and
Son and Holy Spirit.

Here is a clarifying video about how faith and reason work together.

#+html: <iframe width="560" height="315" src="https://www.youtube.com/embed/sfqgGRNr2ws?si=VUiZ3HY8WDWBBGkc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

For an excellent discussion on faith and reason, you may wish to read the
encyclical [[https://www.vatican.va/content/john-paul-ii/en/encyclicals/documents/hf_jp-ii_enc_14091998_fides-et-ratio.html][/Fides et Ratio/]] by Pope St. John Paul II.


** Summary

In addition to having shown that there must be truth and truth must be absolute,
we also have acquired the principle of non-contradiction. This is very
important, because it allows us to identify and reject ideas which are invalid
based on contradictions within the ideas themselves. I believe this is also a
tool for theology: something cannot be both true and false at the same time in
the realm of faith. Such a theological proposition would contradict itself, and
it would be invalid.

** Applications of Truth
:PROPERTIES:
:CUSTOM_ID: truth-applied
:END:

Now that we know that truth exists and it is absolute, we are in a position to
apply it. We can do so in a few ways. I will use it to argue the following:
1. The universe tells us that there is a God. It doesn't necessarily tell us
   directly that God is like the God of Christians, but it leads us to something
   that fits the kind of being in which Christians believe to be God, along with
   the faithful of other religions. To know more about this being, we would need
   to spend more time discussing the revelation given to us by reason and
   nature, or we need to add divine revelation.

   #+begin_info
   #+html: <a id="what-is-god"><b>What is God?</b></a>

   #+html: <details>
   #+html: <summary>Read more ...</summary>


   To learn what God is like, we can look to the universe. We can argue the
   following:
   1. Anything that has a beginning has a cause.
   2. The universe has a beginning.
      There are two ways to support this:
      1. Using evidence from science.
      2. Using reason alone.
         1. If the universe has no beginning, it would have endured for an infinite
            amount of time to arrive at the present.
         2. It is impossible to traverse an infinite period of time to arrive at the
   3. Thus, the universe has a cause.

   It turns out that the universe has plenty to tell us about its cause. The
   universe contains all matter, energy, space, and time--or else it wouldn't be 
   the universe. Since the universe contains all matter, energy, space and time,
   its cause must be independent of each of these. In other words, the cause of
   the universe must be immaterial (independent of matter, energy, and space) as
   well as eternal (independent or outside of time). At this point, the cause of
   the universe begins to match the characteristic of the entity Christians and
   adherents of other faiths call /God/. And since this cause of the universe is
   outside of space and time, we can say that it is unchanging, for without time,
   there is no change.

   What we have learned about the cause of the universe appears to be lacking some
   features of what Christians call God. In particular, the universe does not
   immediately indicate that its cause has a personality. That is, we have not yet
   established that the cause of the universe is a /personal/ entity.

   Now, we may ask, what could cause the unchanging cause of the universe to create
   the universe? If the cause of the universe is unchanging, then nothing could
   make it create a universe. However, such an all-powerful entity /chose/
   to create out of its own free will. To posess a will and the faculty of choice
   could explain the creation of the universe. For the cause of the universe to
   have free will and choice implies personhood or personality within this
   immaterial and eternal cause.

   /God, is that You?/

   #+html: </details>
   #+end_info

   #+begin_info
   #+html: <a id="god-is-being"><b>God does NOT exist!</b></a>
   
   #+html: <details>
   #+html: <summary>Read more (Really? Are you even Christian?!?) ...</summary>

   I declare it's true: God does not exist.

   To understand this, we must understand what /exist/ means. The word "exist"
   comes from Latin: /ex/ means "from, out, outside of," and "ist" comes from /sistere/,
   which means "to set up, to cause to stand." Thus, for something to /exist/
   conveys the sense that it arises from something else.

   While the universe is contingent upon its cause--and as Christians, we believe
   that cause to be God--God is not existent in the sense that His being arises
   from something else. Thus, I claim that *God does not exist*.

   Rather, the fullness of teaching about God is that *God is being itself*. This
   concept says that God is the fundamental source and essence of
   existence. Anything that exists does so by sharing in God's being. If God ceased
   to be, then everything that exists ceases to exist, also.

   This concept of God as being itself aligns with God's self-identification as "I
   AM" ([[https://www.biblegateway.com/passage/?search=Exodus%203%3A14&version=RSVCE][Exodus 3:14]]; and [[https://www.biblegateway.com/passage/?search=John%208%3A58-59&version=RSVCE][John 8:58-59]]). He is not from someone or something else;
   God simply /is/.

   #+html: </details>
   #+end_info

2. You are loved. With the help of some divine revelation and human philosophy,
   follows from the discussion above about God's nature and God's will.

   #+begin_info
   #+html: <a id="you-are-loved"><b>YOU are LOVED</b></a>

   #+html: <details>
   #+html: <summary>Read about how your existence means God loves you ...</summary>
   
   In the Catholic faith, we believe something profound and beautiful: your very
   existence is no accident. The fact that you are alive—right here, right
   now—is a sign that God not only created you, but continues to will your
   existence at every moment. As St. Thomas Aquinas taught, creation isn’t just
   something God did once, long ago. Rather, He holds you in being with every
   breath you take. You exist because God loves you into existence. 

   This is not merely poetic—it is the truth. God is Being itself (“I AM who
   AM,” Exodus 3:14), and everything that exists shares in His being. But unlike
   inanimate things, you are made in the image and likeness of God (Genesis
   1:27). You are a person—capable of knowing, loving, and choosing Him in
   return. That is not something arbitrary. It’s a calling, woven into your very
   being. 

   And so even in the hardest moments—when life feels heavy, when suffering is
   close, when God may even seem distant—the truth remains: if you are alive,
   God is sustaining you. He has not withdrawn His love. In fact, it is often
   precisely in suffering that He opens the door for you to draw closest to Him.

   As the Catechism reminds us ([[https://www.usccb.org/sites/default/files/flipbooks/catechism/14/][CCC 27]]), “the desire for God is written in the
   human heart,” and “God never ceases to draw man to himself.” Suffering
   doesn’t cancel that call—it can deepen it. When we freely choose to trust Him
   in our pain, when we choose to remain open to His presence rather than
   closing in on despair, we are brought nearer to the Cross—and through it, to
   the Resurrection. 

   Jesus Himself did not avoid suffering. He entered it fully, out of love for
   us. And now, in our own trials, we have the opportunity to unite ourselves to
   Him—to know Him not only as Creator and Sustainer, but as the Crucified One
   who is with us, and the Risen One who gives meaning to our pain. St. Paul
   recognized that suffering has a way of uniting us to Christ and revealing His
   love for us ([[https://www.biblegateway.com/passage/?search=Philippians%203%3A7-10&version=NRSVCE][Ephesians 3:7-11, NRSVCE]]):
   #+begin_quote
   7 Yet whatever gains I had, these I have come to regard as loss because of
   Christ. 8 More than that, I regard everything as loss because of the
   surpassing value of knowing Christ Jesus my Lord. For his sake I have
   suffered the loss of all things, and I regard them as rubbish, in order that
   I may gain Christ 9 and be found in him, not having a righteousness of my own
   that comes from the law, but one that comes through faith in Christ, the
   righteousness from God based on faith. 10 I want to *know Christ* and the
   *power of his resurrection* and *the sharing of his sufferings* by becoming like
   him in his death, 11 if somehow I may attain the resurrection from the dead.
   #+end_quote

   So, the fact that you are alive today means this: God is still offering you
   His love, His grace, His very life. He is giving you the chance—moment by
   moment—to choose Him, to seek Him, and to know Him more deeply. Even when the
   path is dark, He walks it with you. 

   *You are here because God, in His Love, /actively/ wills you to be here*. And
   God is not finished with you yet.

   Want to hear this from someone else? Listen to this sound byte from Fr. John
   Riccardo:
   #+html: <iframe width="560" height="315" src="https://www.youtube.com/embed/dmKuSXXXhII?si=SuskicFrMf4-S1DB" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

   #+html: </details>
   #+end_info
   

